packages:
  - domains/*
  - libs/*
  - platform/domains/*
  - platform/infra/*
  - platform/shared
  - platform/smoke-test
  - tests/*
  - tests/performance/*

ignoredBuiltDependencies:
  - msw

minimumReleaseAge: 2880

onlyBuiltDependencies:
  - "@swc/core"
  - esbuild
  - nx

savePrefix: ""
