packages:
  - domains/*
  - libs/*
  - platform/domains/*
  - platform/infra/*
  - platform/internal/gateways/*
  - tests/*

ignoredBuiltDependencies:
  - msw

minimumReleaseAge: 2880

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - nx

savePrefix: ''
