packages:
  - domains/*
  - libs/*
  - platform/domains/*
  - platform/infra/*
  - tests/*
  - tests/performance/*

ignoredBuiltDependencies:
  - msw
  - playwright
  - playwright-core
  - "@playwright/browser-chromium"
  - "@playwright/test"

minimumReleaseAge: 2880

onlyBuiltDependencies:
  - "@swc/core"
  - esbuild
  - nx

savePrefix: ""
