packages:
  - configs/*
  - domains/*
  - libs/*
  - platform/*
  - platform/domains/*
  - platform/infra/*
  - tests/*

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - nx

minimumReleaseAge: 2880
