name: Build & Deploy

on:
  workflow_call:
    inputs:
      AWS_REGION:
        description: "AWS Region to deploy to"
        type: string
      STAGE:
        description: "Development stage"
        type: string
        required: true
    secrets:
      ROLE_TO_ASSUME:
        description: "AWS deployment role to assume"
        required: true

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write # Required for OIDC authentication with AWS
    env:
      STAGE: ${{ inputs.STAGE }}
    environment: ${{ inputs.STAGE }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: |
          npm install -g pnpm@latest-10
          pnpm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@51635dbf418c2cdd8b3e1497529334d8db7e4063 # v5.1.1
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ${{ inputs.AWS_REGION }}
          role-session-name: ${{ github.run_id }}

      - name: Deploy FLEX AWS infra
        run: cd ./platform/infra/flex && pnpm run deploy --require-approval never

      - name: E2E tests
        env:
          STAGE: ${{ env.STAGE }}
        run: pnpm --filter @flex/e2e test:e2e
