name: Release Candidate

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: false

jobs:
  validate-openapi:
    name: Validate Open API Spec
    uses: ./.github/workflows/_validate-openapi.yml
    secrets:
      ROLE_TO_ASSUME: ${{ secrets.DEV_DEPLOYMENT_ROLE }}

  quality-checks:
    name: Quality Checks
    uses: ./.github/workflows/_quality-checks.yml
    with:
      AWS_REGION: "eu-west-2"
      STAGE: "development"
    secrets:
      ROLE_TO_ASSUME: ${{ secrets.DEV_DEPLOYMENT_ROLE }}
      SONAR_TOKEN_FLEX: ${{ secrets.SONAR_TOKEN_FLEX }}
      SONAR_URL: ${{ secrets.SONAR_URL }}

  ephemeral-env:
    name: Ephemeral Environment branch tests
    uses: ./.github/workflows/_build-deploy.yml
    with:
      AWS_REGION: "eu-west-2"
      STAGE: pr-${{ github.event.pull_request.number }}
    secrets:
      ROLE_TO_ASSUME: ${{ secrets.DEV_DEPLOYMENT_ROLE }}

  moduleE2E:
    name: Module E2E
    needs: ephemeral-env
    uses: ./.github/workflows/_moduleE2E.yml
    with:
      AWS_REGION: 'eu-west-2'
      STAGE: pr-${{ github.event.pull_request.number }}
    secrets:
      ROLE_TO_ASSUME: ${{ secrets.DEV_DEPLOYMENT_ROLE }}
