name: Destroy Ephemeral Environment

on:
  pull_request:
    types: [closed]

permissions:
  id-token: write # Required for AWS OIDC
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      STAGE: pr-${{ github.event.pull_request.number }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: |
          npm install -g pnpm@latest-10
          pnpm install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@51635dbf418c2cdd8b3e1497529334d8db7e4063 # v5.1.1
        with:
          role-to-assume: ${{ secrets.DEV_DEPLOYMENT_ROLE }}
          aws-region: eu-west-2
          role-session-name: ${{ github.run_id }}

      - name: Destroy Stack
        run: cd ./platform/infra/flex && pnpm run destroy --force
